### ISSUE TITLE
std::vector<std::string> argument?

### ISSUE THREAD

**Issue by Phygon** [ttauri-project/ttauri#2]
https://github.com/ttauri-project/ttauri/blob/a09bb9445918fed401c46b1f50aeffb12b76e5cd/src/ttauri/crt.hpp#L43

While it might be a good idea to modernize the argument handling of main(), I have two comments:
1) In C++20, I would expect a vector< string_view > instead of vector< string >
2) There should be an option for a argc/argv version, as otherwise this can be incompatible with a bunch of 3rd party libraries, which expect argv/argc for example: command line parsing (boost::program_options and similar), CORBA...

If using tt_main() is optional for ttauri, 2) can be ignored.

**Comment by takev** [comment]
tt_main() is indeed optional. But your comment about argc/argv and other APIs is valid.

I may change tt_main() to have the normal argc/argv interface. I did it with std::vector<std::string> because windows requires conversion of the arguments to unescape and split into separate arguments, but there is no reason this cannot be done with old style argc/argv.
