### ISSUE TITLE
Custom Widget Example

### ISSUE THREAD

**Issue by shujaatak** [ttauri-project/ttauri#211]
Can you please add an example to show how to create our own custom widget using ttauri?

**Comment by takev** [comment]
It is a good idea.

But a lot of documentation needs to be done for this.

Although i stabilised how widgets should be used, the internals of widgets are still a bit in flux. Specifically the drawing context is still a bit inconsistent.

**Comment by takev** [comment]
Another update; working on the draw_context and making all draw function consistent with each other.
I want all function to accept a quad, so transforms need not be passed. Already got that working for box and sdf  shaders,but not yet the image shader.

**Comment by takev** [comment]
Another update; reworked `draw_context::draw_image()`. Now all draw commands except draw_text will take a `quad` as argument to draw inside the quad whatever its orientation or location. draw_text still accepts a transform, because it draws multiple quads inside it (one for each glyph), I believe it should remain how it works now.

The icon_widget is now a bit simpler due to it not needing knowledge of vulkan anymore.

**Comment by takev** [comment]
update: looks most of the programming work is done.
Next will be to make custom widget examples and documentation.

**Comment by takev** [comment]
Update: first two (non interactive) example widgets
